#!/usr/bin/env bash
# ascii

dragon1='                \||/
                |  @___oo
      /\  /\   / (__,,,,|
     ) /^\) ^\/ _)
     )   /^\/   _)
     )   _ /  / _)
 /\  )/\/ ||  | )_)
<  >      |(,,) )__)
 ||      /    \)___)\
 | \____(      )___) )___
  \______(_______;;; __;;;
'

declare -r dragon1

echo "DRAGON:"
echo "${dragon1}"
exit
