#!/usr/bin/env bash
# ascii

declare windleaf
windleaf="
d888888b .88b  d88.    .d8b.    db      d88888b  .d8b.  d88888b 
  \`88'   88'YbdP\`88   d8' \`8b   88      88'     d8' \`8b 88'     
   88    88  88  88   88ooo88   88      88ooooo 88ooo88 88ooo   
   88    88  88  88   88~~~88   88      88~~~~~ 88~~~88 88~~~   
  .88.   88  88  88   88   88   88booo. 88.     88   88 88      
Y888888P YP  YP  YP   YP   YP   Y88888P Y88888P YP   YP YP      
                                                                
                                                                
 .d88b.  d8b   db   d888888b db   db d88888b 
.8P  Y8. 888o  88   \`~~88~~' 88   88 88'     
88    88 88V8o 88      88    88ooo88 88ooooo 
88    88 88 V8o88      88    88~~~88 88~~~~~ 
\`8b  d8' 88  V888      88    88   88 88.     
 \`Y88P'  VP   V8P      YP    YP   YP Y88888P 
                                             
                                             
db   d8b   db d888888b d8b   db d8888b. 
88   I8I   88   \`88'   888o  88 88  \`8D 
88   I8I   88    88    88V8o 88 88   88 
Y8   I8I   88    88    88 V8o88 88   88 
\`8b d8'8b d8'   .88.   88  V888 88  .8D 
 \`8b8' \`8d8'  Y888888P VP   V8P Y8888D' 
 "


echo "${windleaf}" > ~/.logg

